# Generated by Django 4.2.16 on 2026-03-30 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Our Institution', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Short bold tagline', max_length=300)),
                ('description', models.TextField(help_text='Main about us description (supports HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('founded_year', models.CharField(blank=True, help_text='e.g. 1985', max_length=10)),
                ('students_count', models.CharField(blank=True, help_text='e.g. 12,000+', max_length=20)),
                ('faculty_count', models.CharField(blank=True, help_text='e.g. 500+', max_length=20)),
                ('programs_count', models.CharField(blank=True, help_text='e.g. 80+', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto or manual)', unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short preview text for listing page', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content (supports HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g. Events, Research, Campus Life', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read once reviewed')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, help_text='e.g. Campus, Events, Sports', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_visible', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline shown on hero', max_length=200)),
                ('subtitle', models.TextField(help_text='Supporting text below the title')),
                ('background_image', models.ImageField(blank=True, help_text='Upload a fullscreen background image (JPG/PNG recommended)', null=True, upload_to='hero/')),
                ('background_video', models.FileField(blank=True, help_text='Upload a background video (MP4). Video takes priority over image if both set.', null=True, upload_to='hero/videos/')),
                ('cta_text', models.CharField(default='Explore Now', help_text='Call-to-action button text', max_length=100)),
                ('cta_link', models.CharField(default='#about', help_text='CTA button target link', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only one hero section should be active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='Apex University', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_text', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
